# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Bus.create([
  { name: 'NA' },
  { name: 'PARALLEL' },
  { name: 'I2C' },
  { name: 'SPI' },
  { name: 'UART' },
  { name: 'SWD' }
])

ChipType.create([
  { name: 'MEMORY' },
  { name: 'MICROCONTROLER' }
])

Signall.create([
  {name: 'NA',       pin: 'A0' },
  {name: 'A0',       pin: 'A0' },
  {name: 'A1',       pin: 'A1' },
  {name: 'A2',       pin: 'A2' },
  {name: 'A3',       pin: 'A3' },
  {name: 'A4',       pin: 'A4' },
  {name: 'A5',       pin: 'A5' },
  {name: 'A6',       pin: 'A6' },
  {name: 'A7',       pin: 'A7' },
  {name: 'A8',       pin: 'B0' },
  {name: 'A9',       pin: 'B1' },
  {name: 'A10',      pin: 'B2' },
  {name: 'A11',      pin: 'B3' },
  {name: 'A12',      pin: 'B4' },
  {name: 'A13',      pin: 'B5' },
  {name: 'A14',      pin: 'B6' },
  {name: 'A15',      pin: 'B7' },
  {name: 'A16',      pin: 'C0' },
  {name: 'A17',      pin: 'C1' },
  {name: 'A18',      pin: 'C2' },
  {name: 'A19',      pin: 'C3' },
  {name: 'A20',      pin: 'C4' },
  {name: 'A21',      pin: 'C5' },
  {name: 'A22',      pin: 'C6' },
  {name: 'A23',      pin: 'C7' },
  {name: 'A24',      pin: 'E0' },
  {name: 'A25',      pin: 'E1' },
  {name: 'A26',      pin: 'E2' },
  {name: 'A27',      pin: 'E3' },
  {name: 'A28',      pin: 'E4' },
  {name: 'A29',      pin: 'E5' },
  {name: 'A30',      pin: 'E6' },
  {name: 'A31',      pin: 'E7' },
  {name: 'D0',       pin: 'F0' },
  {name: 'D1',       pin: 'F1' },
  {name: 'D2',       pin: 'F2' },
  {name: 'D3',       pin: 'F3' },
  {name: 'D4',       pin: 'F4' },
  {name: 'D5',       pin: 'F5' },
  {name: 'D6',       pin: 'F6' },
  {name: 'D7',       pin: 'F7' },
  {name: 'D8',       pin: 'G0' },
  {name: 'D9',       pin: 'G1' },
  {name: 'D10',      pin: 'G2' },
  {name: 'D11',      pin: 'G3' },
  {name: 'D12',      pin: 'G4' },
  {name: 'D13',      pin: 'G5' },
  {name: 'D14',      pin: 'G6' },
  {name: 'D15',      pin: 'G7' },
  {name: 'RST',      pin: 'H0' },
  {name: 'CE',       pin: 'H1' },
  {name: 'OE',       pin: 'H2' },
  {name: 'WE',       pin: 'H3' },
  {name: 'WP',       pin: 'H5' },
  {name: 'ADV',      pin: 'H6' },
  {name: 'PARA_CLK', pin: 'H4' },
  {name: 'SDA',      pin: 'A1' },
  {name: 'I2C_CLK',  pin: 'A0' },
  {name: 'CS',       pin: 'A0' },
  {name: 'MOSI',     pin: 'A2' },
  {name: 'MISO',     pin: 'A3' },
  {name: 'SPI_CLK',  pin: 'A1' },
  {name: 'PULSE',  	 pin: 'A4' },
  {name: 'TX',  	 	 pin: 'A0' },
  {name: 'RX',  	 	 pin: 'A1' },
  {name: 'SWD_CLK',  pin: 'A0' },
  {name: 'SWD_IO',   pin: 'A1' }
])

Use.create([
  {bus_id: 1, signal_id: 1},
  {bus_id: 2, signal_id: 2},
  {bus_id: 2, signal_id: 3},
  {bus_id: 2, signal_id: 4},
  {bus_id: 2, signal_id: 5},
  {bus_id: 2, signal_id: 6},
  {bus_id: 2, signal_id: 7},
  {bus_id: 2, signal_id: 8},
  {bus_id: 2, signal_id: 9},
  {bus_id: 2, signal_id: 10},
  {bus_id: 2, signal_id: 11},
  {bus_id: 2, signal_id: 12},
  {bus_id: 2, signal_id: 13},
  {bus_id: 2, signal_id: 14},
  {bus_id: 2, signal_id: 15},
  {bus_id: 2, signal_id: 16},
  {bus_id: 2, signal_id: 17},
  {bus_id: 2, signal_id: 18},
  {bus_id: 2, signal_id: 19},
  {bus_id: 2, signal_id: 20},
  {bus_id: 2, signal_id: 21},
  {bus_id: 2, signal_id: 22},
  {bus_id: 2, signal_id: 23},
  {bus_id: 2, signal_id: 24},
  {bus_id: 2, signal_id: 25},
  {bus_id: 2, signal_id: 26},
  {bus_id: 2, signal_id: 27},
  {bus_id: 2, signal_id: 28},
  {bus_id: 2, signal_id: 29},
  {bus_id: 2, signal_id: 30},
  {bus_id: 2, signal_id: 31},
  {bus_id: 2, signal_id: 32},
  {bus_id: 2, signal_id: 33},
  {bus_id: 2, signal_id: 34},
  {bus_id: 2, signal_id: 35},
  {bus_id: 2, signal_id: 36},
  {bus_id: 2, signal_id: 37},
  {bus_id: 2, signal_id: 38},
  {bus_id: 2, signal_id: 39},
  {bus_id: 2, signal_id: 40},
  {bus_id: 2, signal_id: 41},
  {bus_id: 2, signal_id: 42},
  {bus_id: 2, signal_id: 43},
  {bus_id: 2, signal_id: 44},
  {bus_id: 2, signal_id: 45},
  {bus_id: 2, signal_id: 46},
  {bus_id: 2, signal_id: 47},
  {bus_id: 2, signal_id: 48},
  {bus_id: 2, signal_id: 49},
  {bus_id: 2, signal_id: 50},
  {bus_id: 2, signal_id: 51},
  {bus_id: 2, signal_id: 52},
  {bus_id: 2, signal_id: 53},
  {bus_id: 2, signal_id: 54},
  {bus_id: 2, signal_id: 55},
  {bus_id: 2, signal_id: 56},
  {bus_id: 3, signal_id: 57},
  {bus_id: 3, signal_id: 58},
  {bus_id: 4, signal_id: 59},
  {bus_id: 4, signal_id: 60},
  {bus_id: 4, signal_id: 61},
  {bus_id: 4, signal_id: 62},
  {bus_id: 4, signal_id: 63},
  {bus_id: 5, signal_id: 64},
  {bus_id: 5, signal_id: 65},
  {bus_id: 6, signal_id: 66},
  {bus_id: 6, signal_id: 67}
])
